# Generated by Django 5.1.7 on 2025-04-02 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('general', 'General'), ('diseño_web', 'Diseño Web'), ('desarrollo_web', 'Desarrollo Web')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='articulos'),
        ),
    ]
