# Generated by Django 5.1.7 on 2025-04-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articulo_categoria_articulo_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default=' ')),
                ('autor', models.CharField(max_length=60)),
                ('articul', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.articulo')),
            ],
        ),
    ]
