# Generated by Django 5.1.7 on 2025-04-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(default='anonimo', max_length=60),
        ),
    ]
